registry_treatment_list:
    path: '/liste'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:listAction'

registry_treatment_create:
    path: '/creer'
    methods: ['GET', 'POST']
    controller: 'App\Domain\Registry\Controller\TreatmentController:createAction'

registry_treatment_edit:
    path: '/editer/{id}'
    methods: ['GET', 'POST']
    controller: 'App\Domain\Registry\Controller\TreatmentController:editAction'

registry_treatment_show:
    path: '/visualiser/{id}'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:showAction'

registry_treatment_report:
    path: '/bilan'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:reportAction'

registry_treatment_print_all:
    path: '/imprimer-tous'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:pdfAllAction'

registry_treatment_archive_all:
    path: '/archiver'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:archiveAllAction'

registry_treatment_archive_all_confirm:
  path: '/archiver/confirmation'
  methods: ['GET']
  controller: 'App\Domain\Registry\Controller\TreatmentController:archiveConfirmationAction'

registry_treatment_delete:
    path: '/supprimer/{id}'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:deleteAction'

registry_treatment_delete_all:
    path: '/supprimer-tous/'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:deleteAllAction'

registry_treatment_delete_confirm:
    path: '/supprimer/{id}/confirmation'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:deleteConfirmationAction'

registry_treatment_delete_all_confirm:
    path: '/supprimer-tous/confirmation'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:deleteConfirmationAllAction'

api_registry_treatment_collectivity:
    path: '/api/collectivite/{collectivityId}'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:apiGetTreatmentsByCollectivity'

registry_treatment_pdf:
    path: '/pdf/{id}'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\TreatmentController:pdfAction'

registry_treatment_configuration:
    path: '/configuration'
    methods: ['GET', 'POST']
    controller: 'App\Domain\Registry\Controller\TreatmentController:configurationAction'

registry_treatment_list_datatables:
    path: '/datatables'
    methods: ['POST']
    controller: 'App\Domain\Registry\Controller\TreatmentController:listDataTables'

registry_treatment_request_show:
    path: '../demandes-des-personnes-concernees/visualiser/{id}'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\RequestController:showAction'

registry_treatment_violation_show:
    path: '../violations/visualiser/{id}'
    methods: ['GET']
    controller: 'App\Domain\Registry\Controller\ViolationController:showAction'